# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(CMAKE_COMMAND) -E cmake_progress_start /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master/CMakeFiles /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master/examples/lab3//CMakeFiles/progress.marks
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 examples/lab3/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 examples/lab3/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 examples/lab3/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 examples/lab3/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
examples/lab3/CMakeFiles/lab3.dir/rule:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 examples/lab3/CMakeFiles/lab3.dir/rule
.PHONY : examples/lab3/CMakeFiles/lab3.dir/rule

# Convenience name for target.
lab3: examples/lab3/CMakeFiles/lab3.dir/rule

.PHONY : lab3

# fast build rule for target.
lab3/fast:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/build
.PHONY : lab3/fast

Application.o: Application.cpp.o

.PHONY : Application.o

# target to build an object file
Application.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Application.cpp.o
.PHONY : Application.cpp.o

Application.i: Application.cpp.i

.PHONY : Application.i

# target to preprocess a source file
Application.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Application.cpp.i
.PHONY : Application.cpp.i

Application.s: Application.cpp.s

.PHONY : Application.s

# target to generate assembly for a file
Application.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Application.cpp.s
.PHONY : Application.cpp.s

Camera.o: Camera.cpp.o

.PHONY : Camera.o

# target to build an object file
Camera.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Camera.cpp.o
.PHONY : Camera.cpp.o

Camera.i: Camera.cpp.i

.PHONY : Camera.i

# target to preprocess a source file
Camera.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Camera.cpp.i
.PHONY : Camera.cpp.i

Camera.s: Camera.cpp.s

.PHONY : Camera.s

# target to generate assembly for a file
Camera.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Camera.cpp.s
.PHONY : Camera.cpp.s

DepthCameraSetPositionCallback.o: DepthCameraSetPositionCallback.cpp.o

.PHONY : DepthCameraSetPositionCallback.o

# target to build an object file
DepthCameraSetPositionCallback.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/DepthCameraSetPositionCallback.cpp.o
.PHONY : DepthCameraSetPositionCallback.cpp.o

DepthCameraSetPositionCallback.i: DepthCameraSetPositionCallback.cpp.i

.PHONY : DepthCameraSetPositionCallback.i

# target to preprocess a source file
DepthCameraSetPositionCallback.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/DepthCameraSetPositionCallback.cpp.i
.PHONY : DepthCameraSetPositionCallback.cpp.i

DepthCameraSetPositionCallback.s: DepthCameraSetPositionCallback.cpp.s

.PHONY : DepthCameraSetPositionCallback.s

# target to generate assembly for a file
DepthCameraSetPositionCallback.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/DepthCameraSetPositionCallback.cpp.s
.PHONY : DepthCameraSetPositionCallback.cpp.s

DrawCameraStatus.o: DrawCameraStatus.cpp.o

.PHONY : DrawCameraStatus.o

# target to build an object file
DrawCameraStatus.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/DrawCameraStatus.cpp.o
.PHONY : DrawCameraStatus.cpp.o

DrawCameraStatus.i: DrawCameraStatus.cpp.i

.PHONY : DrawCameraStatus.i

# target to preprocess a source file
DrawCameraStatus.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/DrawCameraStatus.cpp.i
.PHONY : DrawCameraStatus.cpp.i

DrawCameraStatus.s: DrawCameraStatus.cpp.s

.PHONY : DrawCameraStatus.s

# target to generate assembly for a file
DrawCameraStatus.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/DrawCameraStatus.cpp.s
.PHONY : DrawCameraStatus.cpp.s

FPSCounter.o: FPSCounter.cpp.o

.PHONY : FPSCounter.o

# target to build an object file
FPSCounter.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/FPSCounter.cpp.o
.PHONY : FPSCounter.cpp.o

FPSCounter.i: FPSCounter.cpp.i

.PHONY : FPSCounter.i

# target to preprocess a source file
FPSCounter.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/FPSCounter.cpp.i
.PHONY : FPSCounter.cpp.i

FPSCounter.s: FPSCounter.cpp.s

.PHONY : FPSCounter.s

# target to generate assembly for a file
FPSCounter.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/FPSCounter.cpp.s
.PHONY : FPSCounter.cpp.s

GPUParticles.o: GPUParticles.cpp.o

.PHONY : GPUParticles.o

# target to build an object file
GPUParticles.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/GPUParticles.cpp.o
.PHONY : GPUParticles.cpp.o

GPUParticles.i: GPUParticles.cpp.i

.PHONY : GPUParticles.i

# target to preprocess a source file
GPUParticles.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/GPUParticles.cpp.i
.PHONY : GPUParticles.cpp.i

GPUParticles.s: GPUParticles.cpp.s

.PHONY : GPUParticles.s

# target to generate assembly for a file
GPUParticles.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/GPUParticles.cpp.s
.PHONY : GPUParticles.cpp.s

Geometry.o: Geometry.cpp.o

.PHONY : Geometry.o

# target to build an object file
Geometry.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Geometry.cpp.o
.PHONY : Geometry.cpp.o

Geometry.i: Geometry.cpp.i

.PHONY : Geometry.i

# target to preprocess a source file
Geometry.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Geometry.cpp.i
.PHONY : Geometry.cpp.i

Geometry.s: Geometry.cpp.s

.PHONY : Geometry.s

# target to generate assembly for a file
Geometry.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Geometry.cpp.s
.PHONY : Geometry.cpp.s

Group.o: Group.cpp.o

.PHONY : Group.o

# target to build an object file
Group.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Group.cpp.o
.PHONY : Group.cpp.o

Group.i: Group.cpp.i

.PHONY : Group.i

# target to preprocess a source file
Group.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Group.cpp.i
.PHONY : Group.cpp.i

Group.s: Group.cpp.s

.PHONY : Group.s

# target to generate assembly for a file
Group.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Group.cpp.s
.PHONY : Group.cpp.s

LOD.o: LOD.cpp.o

.PHONY : LOD.o

# target to build an object file
LOD.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/LOD.cpp.o
.PHONY : LOD.cpp.o

LOD.i: LOD.cpp.i

.PHONY : LOD.i

# target to preprocess a source file
LOD.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/LOD.cpp.i
.PHONY : LOD.cpp.i

LOD.s: LOD.cpp.s

.PHONY : LOD.s

# target to generate assembly for a file
LOD.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/LOD.cpp.s
.PHONY : LOD.cpp.s

Light.o: Light.cpp.o

.PHONY : Light.o

# target to build an object file
Light.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Light.cpp.o
.PHONY : Light.cpp.o

Light.i: Light.cpp.i

.PHONY : Light.i

# target to preprocess a source file
Light.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Light.cpp.i
.PHONY : Light.cpp.i

Light.s: Light.cpp.s

.PHONY : Light.s

# target to generate assembly for a file
Light.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Light.cpp.s
.PHONY : Light.cpp.s

LightMoveCallback.o: LightMoveCallback.cpp.o

.PHONY : LightMoveCallback.o

# target to build an object file
LightMoveCallback.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/LightMoveCallback.cpp.o
.PHONY : LightMoveCallback.cpp.o

LightMoveCallback.i: LightMoveCallback.cpp.i

.PHONY : LightMoveCallback.i

# target to preprocess a source file
LightMoveCallback.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/LightMoveCallback.cpp.i
.PHONY : LightMoveCallback.cpp.i

LightMoveCallback.s: LightMoveCallback.cpp.s

.PHONY : LightMoveCallback.s

# target to generate assembly for a file
LightMoveCallback.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/LightMoveCallback.cpp.s
.PHONY : LightMoveCallback.cpp.s

Loader.o: Loader.cpp.o

.PHONY : Loader.o

# target to build an object file
Loader.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Loader.cpp.o
.PHONY : Loader.cpp.o

Loader.i: Loader.cpp.i

.PHONY : Loader.i

# target to preprocess a source file
Loader.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Loader.cpp.i
.PHONY : Loader.cpp.i

Loader.s: Loader.cpp.s

.PHONY : Loader.s

# target to generate assembly for a file
Loader.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Loader.cpp.s
.PHONY : Loader.cpp.s

Material.o: Material.cpp.o

.PHONY : Material.o

# target to build an object file
Material.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Material.cpp.o
.PHONY : Material.cpp.o

Material.i: Material.cpp.i

.PHONY : Material.i

# target to preprocess a source file
Material.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Material.cpp.i
.PHONY : Material.cpp.i

Material.s: Material.cpp.s

.PHONY : Material.s

# target to generate assembly for a file
Material.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Material.cpp.s
.PHONY : Material.cpp.s

Node.o: Node.cpp.o

.PHONY : Node.o

# target to build an object file
Node.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Node.cpp.o
.PHONY : Node.cpp.o

Node.i: Node.cpp.i

.PHONY : Node.i

# target to preprocess a source file
Node.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Node.cpp.i
.PHONY : Node.cpp.i

Node.s: Node.cpp.s

.PHONY : Node.s

# target to generate assembly for a file
Node.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Node.cpp.s
.PHONY : Node.cpp.s

OrthographicCamera.o: OrthographicCamera.cpp.o

.PHONY : OrthographicCamera.o

# target to build an object file
OrthographicCamera.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/OrthographicCamera.cpp.o
.PHONY : OrthographicCamera.cpp.o

OrthographicCamera.i: OrthographicCamera.cpp.i

.PHONY : OrthographicCamera.i

# target to preprocess a source file
OrthographicCamera.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/OrthographicCamera.cpp.i
.PHONY : OrthographicCamera.cpp.i

OrthographicCamera.s: OrthographicCamera.cpp.s

.PHONY : OrthographicCamera.s

# target to generate assembly for a file
OrthographicCamera.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/OrthographicCamera.cpp.s
.PHONY : OrthographicCamera.cpp.s

PerspectiveCamera.o: PerspectiveCamera.cpp.o

.PHONY : PerspectiveCamera.o

# target to build an object file
PerspectiveCamera.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/PerspectiveCamera.cpp.o
.PHONY : PerspectiveCamera.cpp.o

PerspectiveCamera.i: PerspectiveCamera.cpp.i

.PHONY : PerspectiveCamera.i

# target to preprocess a source file
PerspectiveCamera.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/PerspectiveCamera.cpp.i
.PHONY : PerspectiveCamera.cpp.i

PerspectiveCamera.s: PerspectiveCamera.cpp.s

.PHONY : PerspectiveCamera.s

# target to generate assembly for a file
PerspectiveCamera.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/PerspectiveCamera.cpp.s
.PHONY : PerspectiveCamera.cpp.s

RenderToTexture.o: RenderToTexture.cpp.o

.PHONY : RenderToTexture.o

# target to build an object file
RenderToTexture.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/RenderToTexture.cpp.o
.PHONY : RenderToTexture.cpp.o

RenderToTexture.i: RenderToTexture.cpp.i

.PHONY : RenderToTexture.i

# target to preprocess a source file
RenderToTexture.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/RenderToTexture.cpp.i
.PHONY : RenderToTexture.cpp.i

RenderToTexture.s: RenderToTexture.cpp.s

.PHONY : RenderToTexture.s

# target to generate assembly for a file
RenderToTexture.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/RenderToTexture.cpp.s
.PHONY : RenderToTexture.cpp.s

RenderVisitor.o: RenderVisitor.cpp.o

.PHONY : RenderVisitor.o

# target to build an object file
RenderVisitor.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/RenderVisitor.cpp.o
.PHONY : RenderVisitor.cpp.o

RenderVisitor.i: RenderVisitor.cpp.i

.PHONY : RenderVisitor.i

# target to preprocess a source file
RenderVisitor.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/RenderVisitor.cpp.i
.PHONY : RenderVisitor.cpp.i

RenderVisitor.s: RenderVisitor.cpp.s

.PHONY : RenderVisitor.s

# target to generate assembly for a file
RenderVisitor.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/RenderVisitor.cpp.s
.PHONY : RenderVisitor.cpp.s

RotateCallback.o: RotateCallback.cpp.o

.PHONY : RotateCallback.o

# target to build an object file
RotateCallback.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/RotateCallback.cpp.o
.PHONY : RotateCallback.cpp.o

RotateCallback.i: RotateCallback.cpp.i

.PHONY : RotateCallback.i

# target to preprocess a source file
RotateCallback.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/RotateCallback.cpp.i
.PHONY : RotateCallback.cpp.i

RotateCallback.s: RotateCallback.cpp.s

.PHONY : RotateCallback.s

# target to generate assembly for a file
RotateCallback.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/RotateCallback.cpp.s
.PHONY : RotateCallback.cpp.s

Shadowmap.o: Shadowmap.cpp.o

.PHONY : Shadowmap.o

# target to build an object file
Shadowmap.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Shadowmap.cpp.o
.PHONY : Shadowmap.cpp.o

Shadowmap.i: Shadowmap.cpp.i

.PHONY : Shadowmap.i

# target to preprocess a source file
Shadowmap.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Shadowmap.cpp.i
.PHONY : Shadowmap.cpp.i

Shadowmap.s: Shadowmap.cpp.s

.PHONY : Shadowmap.s

# target to generate assembly for a file
Shadowmap.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Shadowmap.cpp.s
.PHONY : Shadowmap.cpp.s

Skybox.o: Skybox.cpp.o

.PHONY : Skybox.o

# target to build an object file
Skybox.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Skybox.cpp.o
.PHONY : Skybox.cpp.o

Skybox.i: Skybox.cpp.i

.PHONY : Skybox.i

# target to preprocess a source file
Skybox.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Skybox.cpp.i
.PHONY : Skybox.cpp.i

Skybox.s: Skybox.cpp.s

.PHONY : Skybox.s

# target to generate assembly for a file
Skybox.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Skybox.cpp.s
.PHONY : Skybox.cpp.s

SortedGroup.o: SortedGroup.cpp.o

.PHONY : SortedGroup.o

# target to build an object file
SortedGroup.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/SortedGroup.cpp.o
.PHONY : SortedGroup.cpp.o

SortedGroup.i: SortedGroup.cpp.i

.PHONY : SortedGroup.i

# target to preprocess a source file
SortedGroup.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/SortedGroup.cpp.i
.PHONY : SortedGroup.cpp.i

SortedGroup.s: SortedGroup.cpp.s

.PHONY : SortedGroup.s

# target to generate assembly for a file
SortedGroup.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/SortedGroup.cpp.s
.PHONY : SortedGroup.cpp.s

State.o: State.cpp.o

.PHONY : State.o

# target to build an object file
State.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/State.cpp.o
.PHONY : State.cpp.o

State.i: State.cpp.i

.PHONY : State.i

# target to preprocess a source file
State.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/State.cpp.i
.PHONY : State.cpp.i

State.s: State.cpp.s

.PHONY : State.s

# target to generate assembly for a file
State.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/State.cpp.s
.PHONY : State.cpp.s

Texture.o: Texture.cpp.o

.PHONY : Texture.o

# target to build an object file
Texture.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Texture.cpp.o
.PHONY : Texture.cpp.o

Texture.i: Texture.cpp.i

.PHONY : Texture.i

# target to preprocess a source file
Texture.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Texture.cpp.i
.PHONY : Texture.cpp.i

Texture.s: Texture.cpp.s

.PHONY : Texture.s

# target to generate assembly for a file
Texture.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Texture.cpp.s
.PHONY : Texture.cpp.s

Transform.o: Transform.cpp.o

.PHONY : Transform.o

# target to build an object file
Transform.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Transform.cpp.o
.PHONY : Transform.cpp.o

Transform.i: Transform.cpp.i

.PHONY : Transform.i

# target to preprocess a source file
Transform.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Transform.cpp.i
.PHONY : Transform.cpp.i

Transform.s: Transform.cpp.s

.PHONY : Transform.s

# target to generate assembly for a file
Transform.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/Transform.cpp.s
.PHONY : Transform.cpp.s

UpdateVisitor.o: UpdateVisitor.cpp.o

.PHONY : UpdateVisitor.o

# target to build an object file
UpdateVisitor.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/UpdateVisitor.cpp.o
.PHONY : UpdateVisitor.cpp.o

UpdateVisitor.i: UpdateVisitor.cpp.i

.PHONY : UpdateVisitor.i

# target to preprocess a source file
UpdateVisitor.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/UpdateVisitor.cpp.i
.PHONY : UpdateVisitor.cpp.i

UpdateVisitor.s: UpdateVisitor.cpp.s

.PHONY : UpdateVisitor.s

# target to generate assembly for a file
UpdateVisitor.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/UpdateVisitor.cpp.s
.PHONY : UpdateVisitor.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/main.cpp.s
.PHONY : main.cpp.s

shader_utils.o: shader_utils.cpp.o

.PHONY : shader_utils.o

# target to build an object file
shader_utils.cpp.o:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/shader_utils.cpp.o
.PHONY : shader_utils.cpp.o

shader_utils.i: shader_utils.cpp.i

.PHONY : shader_utils.i

# target to preprocess a source file
shader_utils.cpp.i:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/shader_utils.cpp.i
.PHONY : shader_utils.cpp.i

shader_utils.s: shader_utils.cpp.s

.PHONY : shader_utils.s

# target to generate assembly for a file
shader_utils.cpp.s:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(MAKE) $(MAKESILENT) -f examples/lab3/CMakeFiles/lab3.dir/build.make examples/lab3/CMakeFiles/lab3.dir/shader_utils.cpp.s
.PHONY : shader_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... lab3"
	@echo "... Application.o"
	@echo "... Application.i"
	@echo "... Application.s"
	@echo "... Camera.o"
	@echo "... Camera.i"
	@echo "... Camera.s"
	@echo "... DepthCameraSetPositionCallback.o"
	@echo "... DepthCameraSetPositionCallback.i"
	@echo "... DepthCameraSetPositionCallback.s"
	@echo "... DrawCameraStatus.o"
	@echo "... DrawCameraStatus.i"
	@echo "... DrawCameraStatus.s"
	@echo "... FPSCounter.o"
	@echo "... FPSCounter.i"
	@echo "... FPSCounter.s"
	@echo "... GPUParticles.o"
	@echo "... GPUParticles.i"
	@echo "... GPUParticles.s"
	@echo "... Geometry.o"
	@echo "... Geometry.i"
	@echo "... Geometry.s"
	@echo "... Group.o"
	@echo "... Group.i"
	@echo "... Group.s"
	@echo "... LOD.o"
	@echo "... LOD.i"
	@echo "... LOD.s"
	@echo "... Light.o"
	@echo "... Light.i"
	@echo "... Light.s"
	@echo "... LightMoveCallback.o"
	@echo "... LightMoveCallback.i"
	@echo "... LightMoveCallback.s"
	@echo "... Loader.o"
	@echo "... Loader.i"
	@echo "... Loader.s"
	@echo "... Material.o"
	@echo "... Material.i"
	@echo "... Material.s"
	@echo "... Node.o"
	@echo "... Node.i"
	@echo "... Node.s"
	@echo "... OrthographicCamera.o"
	@echo "... OrthographicCamera.i"
	@echo "... OrthographicCamera.s"
	@echo "... PerspectiveCamera.o"
	@echo "... PerspectiveCamera.i"
	@echo "... PerspectiveCamera.s"
	@echo "... RenderToTexture.o"
	@echo "... RenderToTexture.i"
	@echo "... RenderToTexture.s"
	@echo "... RenderVisitor.o"
	@echo "... RenderVisitor.i"
	@echo "... RenderVisitor.s"
	@echo "... RotateCallback.o"
	@echo "... RotateCallback.i"
	@echo "... RotateCallback.s"
	@echo "... Shadowmap.o"
	@echo "... Shadowmap.i"
	@echo "... Shadowmap.s"
	@echo "... Skybox.o"
	@echo "... Skybox.i"
	@echo "... Skybox.s"
	@echo "... SortedGroup.o"
	@echo "... SortedGroup.i"
	@echo "... SortedGroup.s"
	@echo "... State.o"
	@echo "... State.i"
	@echo "... State.s"
	@echo "... Texture.o"
	@echo "... Texture.i"
	@echo "... Texture.s"
	@echo "... Transform.o"
	@echo "... Transform.i"
	@echo "... Transform.s"
	@echo "... UpdateVisitor.o"
	@echo "... UpdateVisitor.i"
	@echo "... UpdateVisitor.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... shader_utils.o"
	@echo "... shader_utils.i"
	@echo "... shader_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/dv19/dv19jbm/Advanced_Computer_Graphics/5dv180-master && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

